### ISSUE TITLE
restoreStateFromArguments throw NullPointerException

### ISSUE THREAD

**Issue by xiaojidonggong** [nuuneoi/StatedFragment#2]
the code:

   private boolean restoreStateFromArguments() {
        Bundle b = getArguments();   //   b is null
        savedState = b.getBundle("internalSavedViewState8954201239547");
        if (savedState != null) {
            restoreState();
            return true;
        }
        return false;
    }

**Comment by cybersam** [comment]
This seems to have been fixed in v0.9.3.

**Comment by nuuneoi** [comment]
Dear tikkat3, it has already been fixed in v0.9.3. Please kindly update your library to the latest version. =)

**Comment by xiaojidonggong** [comment]
@nuuneoi Thank you!
